name: CI/CD Pipeline for College Placement Assistant

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '22.x'
        python-version: '3.10'

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------------------------
      # Setup Python for ML Backend
      # ---------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies (ML API)
        working-directory: ./ml
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask ML API (Basic Check)
        working-directory: ./ml
        run: |
          python main.py &
          sleep 5
          curl --fail http://127.0.0.1:5000 || exit 1

      # -------------------------------
      # Setup Node for Backend & Frontend
      # -------------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # --------- Express Backend ---------
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Lint or test Express backend
        working-directory: ./backend
        run: |
          echo "⚠️ Add backend tests here if available"
          npm run dev & sleep 5

      # --------- React Frontend ---------
      - name: Install frontend dependencies
        working-directory: ./ui
        run: npm install

      - name: Build React Vite frontend
        working-directory: ./ui
        run: npm run build

      - name: Lint or test frontend
        working-directory: ./ui
        run: echo "⚠️ Add frontend tests here if available"

